export const pixelCloudPrompt = `A full-bleed, locked WebGL/three.js animated sky background called PixelCloud, ported from Aceternity UI's Cloud Shader then pixelated. The underlying cloud technique is realistic rather than hand-drawn: each cloud is an asymmetric signed-distance envelope (a dome above its center, a flatter base below, giving the classic rounded-top/flat-bottom cloud silhouette) filled with domain-warped billow noise — noise built from 1 - abs(2 * valueNoise - 1) so it forms sharp puffy ridges like cauliflower tops, with the sample point warped by a second FBM field that slowly evolves over time so the detail crawls rather than just translating. Self-shadowing is faked cheaply by sampling the same density field a second time, offset upward toward the implied sun, and using the difference between the two samples as an occlusion term that darkens the underside of each puff toward the sky color. Six independently seeded clouds drift horizontally at different speeds/phases and wrap around the screen edge, split into far/middle/near depth layers via decreasing drift speed, increasing size, and an atmospheric-perspective fade (more distant clouds blend further into the sky color and lose opacity) — the count prop (1-6) controls how many of these layers render. A vertical sky gradient (skyBottomColor to skyTopColor) plus a faint horizon haze band sits behind everything. To pixelate this normally-smooth, photographic-looking cloud shader: screen coordinates are snapped to a chunky pixel grid (floor(fragCoord / pixelSize) * pixelSize) before every downstream sample, so cloud silhouettes read as blocky/stair-stepped instead of smooth-edged; additionally the raw density field and the self-shadow occlusion term are each quantized into a small number of flat steps (floor(value / step) * step) before shading, replacing the original's smooth gradient shading with flat posterized bands — together these two changes turn the same underlying cloud shapes into flat-shaded pixel art rather than soft realistic clouds, while keeping their drift, depth layering, and self-shadowing intact. Exposed props: cloudColor, skyTopColor, skyBottomColor, speed (global drift multiplier), count (number of cloud layers, 1-6), pixelSize (size in screen px of one pixel-art block — larger reads chunkier/more retro). The React component wraps this in a resizable, IntersectionObserver-gated canvas (pauses rendering when scrolled out of view, debounced resize handling, capped devicePixelRatio, disposes the renderer/geometry/material on unmount, and sets image-rendering: pixelated as a CSS backstop) with className/style passthrough so it composites as a background layer.`;

export const pixelCloudUsage = `import PixelCloud from './PixelCloud';

<div style={{ width: '100%', height: '600px', position: 'relative' }}>
  <PixelCloud
    cloudColor="#fbf8f2"
    skyTopColor="#3876ba"
    skyBottomColor="#8cbfe8"
    speed={1}
    count={6}
    pixelSize={6}
  />
</div>`;
